version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: joshua_notes
      POSTGRES_PASSWORD: "bObjXVzMRMIPOsjl_TXHMFPJo4JCxmsD"
    volumes:
      - joshua_notes_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "vq_C6Z1x4xiLPRptLF6Z08FLc-XmelOy"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  joshua_notes_data:
